[package]
name = "gsbrs"
version = "0.0.1"
authors = ["insanitybit <insanitybit@gmail.com>"]

[dependencies]
hyper = "0.6"
url = "0.2.*"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false

# documentation = "..."
# homepage = "..."
repository = "https://github.com/insanitybit/gsblookup-rs"

description = "Provides a client for Google Safe Browsing lookups"
readme = "https://github.com/insanitybit/gsblookup-rs/blob/master/README.md"

keywords = ["Google", "SafeBrowsing", "gsb"]
license = "MIT"
