[package]
name = "gsbrs"
version = "0.0.1"
authors = ["insanitybit <insanitybit@gmail.com>"]


[dependencies]
hyper = "0.6"
url = "0.2.*"


# documentation = "..."
# homepage = "..."
repository = "https://github.com/insanitybit/gsblookup-rs"

description = "Provides a client for Google Safe Browsing lookups"
readme = "https://github.com/insanitybit/gsblookup-rs/blob/master/README.md"

keywords = ["Google", "SafeBrowsing", "gsb"]
license = "MIT"
